config:
  algorithm: trpo
  rollout_steps: 4000
  num_iterations: 500
  gamma: 0.99
  lam: 0.95
  seed: 42
  env:
    num_tasks: 40 # meta batch size. 40 for loco, 20 for 2dnav
    max_steps: 200
    task_low: 0.0
    task_high: 3.0
    device: cpu
  model:
    hidden_sizes: [100, 100]
  inner:
    lr: 0.1
    advantage_norm: true
  outer:
    lr: 3e-4
    ppo_epochs: 5 # Used for Value Function updates in TRPO
    clip_eps: 0.1
    entropy_coef: 0.0
    value_coef: 0.5
    clip_value_loss: false
    max_grad_norm: 0.5
    advantage_norm: true
  trpo:
    max_kl: 0.01
    damping: 1.0e-2
    cg_iters: 10
    line_search_max_steps: 10
    line_search_backtrack_ratio: 0.5

