algorithm: trpo
rollout_steps: 500
num_iterations: 10000
gamma: 0.99
lam: 0.95
seed: 42
save_interval: 100
env:
  name: mars-lander
  num_tasks: 10
  max_steps: 500
  task_low: 0.0
  task_high: 0.0 # Not used for Mars Lander logic (randomized inside env)
  device: cpu
  norm_obs: false
model:
  hidden_sizes: [100, 100]
inner:
  lr: 0.05
  num_steps: 1
  advantage_norm: false
outer:
  lr: 3e-4
  ppo_epochs: 5
  clip_eps: 0.1
  entropy_coef: 0.0
  value_coef: 0.5
  clip_value_loss: false
  max_grad_norm: 0.5
  advantage_norm: false
trpo:
  max_kl: 0.01
  damping: 1.0e-2
  cg_iters: 10
  line_search_max_steps: 10
  line_search_backtrack_ratio: 0.5
wandb:
  enable: false

